name: Build-Release

on:
  workflow_call:
    inputs:
      release:
        description: 'release'
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/cache@v3
      id: cache-toolchaine
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Rust Toolchain Setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.91.1
        target: wasm32-wasip1
        profile: minimal
        override: true

    - name: Install wasm-snip
      run: |
        cargo install wasm-snip --locked || true

    - name: Test
      run: |
        cargo test

    - name: Compile
      run: |
        cargo build --release
        cargo build --release --target wasm32-wasip1

    - name: Optimize
      run: |
        TARGET=target/wasm32-wasip1/release/nanonanoda.wasm
        if [ ! -f "${TARGET}" ]; then echo "Target not found: ${TARGET}" && ls -la target/wasm32-wasip1/release || exit 1; fi
        wasm-snip "${TARGET}" -o "${TARGET}.snip.wasm"
        mv "${TARGET}.snip.wasm" "${TARGET}"

    - name: Check
      run: |
        TARGET=target/wasm32-wasip1/release/nanonanoda.wasm
        ls -laF "${TARGET}"
        file "${TARGET}" | grep WebAssembly | grep 'version 0x1'
        sha256sum "${TARGET}" | tee "${TARGET}.sha256"

    - uses: ncipollo/release-action@v1
      if: ${{ inputs.release }}
      with:
        artifacts: "target/wasm32-wasip1/release/nanonanoda.wasm, target/wasm32-wasip1/release/nanonanoda.wasm.sha256"
        token: ${{ secrets.GITHUB_TOKEN }}
